### ISSUE TITLE
API 51 upgrade request

### ISSUE THREAD

**Issue by geza-mandli** [superfell/SoqlX#105]
Hi All,

Do you plan to upgrade the API version to 51.0?

There is "select *" in API 51.0 :)

FIELDS(ALL)—to select all the fields of an object.
FIELDS(CUSTOM)—to select all the custom fields of an object.
FIELDS(STANDARD)—to select all the standard fields of an object.

https://developer.salesforce.com/docs/atlas.en-us.soql_sosl.meta/soql_sosl/sforce_api_calls_soql_select_fields.htm

Thanks,
Géza

**Comment by superfell** [comment]
They'll be a version for API 51, not sure when exactly though.

**Comment by superfell** [comment]
v3.5 was just released and includes API v51 support
