### ISSUE TITLE
"Bonk" sound when typing certain closing characters without a matching opening character

### ISSUE THREAD

**Issue by mkdjns** [superfell/SoqlX#113]
**Describe the bug**
In the Apex tab, when typing certain closing characters (`>`, `]`, `)`, `}`) without a matching opening character (`<`, `[`, `)`, `}`), an audible "bonk" sound is heard. While this is potentially useful for alerting on missing characters for collections, etc., it is extremely frustrating when doing comparisons (particularly `>=`, which I do often).

**To Reproduce**
1.  Go to the Apex tab
2. Click into the  Anonymous Apex area
3. Type any of the characters above (`>`, `]`, `)`, `}`), there may be others
4. macOS "bonk" can be heard

**Expected behavior**
No sound please!!

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS 10.15.7
 - SoqlX Version: 3.5
 - Verified on two machines matching the above configuration

**Comment by superfell** [comment]
Yeah, I can see how that'd be annoying. The apex tab uses a library for its syntax highlighting view. It doesn't look like the beep can be configured, nor can the set of characters it considers braces. I'll have a think about what to do.
