### ISSUE TITLE
The object list on the left panel is missing.

### ISSUE THREAD

**Issue by alec-confluent** [superfell/SoqlX#124]
**Describe the bug**
The object list on the left panel is missing.

**To Reproduce**
1. Open the app from the MacOS dock.
2. Let the describe calls finish 

**Expected behavior**
The list of objects with fields in the left panel should show up.  The Schema button does not work either.

**Screenshots**
![Screen Shot 2021-08-16 at 3 20 09 PM](https://user-images.githubusercontent.com/56318004/129636467-b01c592c-7975-45b9-9089-45abbe4e9753.png)

**Desktop (please complete the following information):**
 - OSX 10.14.6
 - SoqlX Version 3.5

**Additional context**
I have tried removing and re-installing the app with no success.  ...I feel I am missing something simple

**Comment by superfell** [comment]
It looks like it got collapsed all the way down to zero. You should be able to click on the left border and drag it open again.

**Comment by alec-confluent** [comment]
YOOOO @superfell you're my hero.  By the way, been a user of this app for a long time and it's a critical tool, thanks for the awesome work!
