### ISSUE TITLE
Newest Version (4.0) Crashes Sometimes when scrolling autocomplete menu in new syntax highlighter

### ISSUE THREAD

**Issue by kensation** [superfell/SoqlX#126]
#### Issue:

Sometimes when I am scrolling in the new autocomplete menu that is a part of the new syntax highlighter SoqlX crashes. It has happened a couple of times today. 

#### Steps to reproduce the behavior:

I was experiencing this when using the autocomplete menu to look at field for related objects a few levels down/over (e.g: SBQQ\_\_QuoteLine\_\_r.SBQQ\_\_RequiredBy\_\_r.SBQQ\_\_Product\_\_r.Name). Not sure how many levels/relationships is too many!

#### Additional Info:

I have attached the crash log that mac OS gave me.

[soqlx-crash-log.txt](https://github.com/superfell/SoqlX/files/7033630/soqlx-crash-log.txt)

**Comment by superfell** [comment]
Thanks for the report and crash log, I'll look into this.
