### ISSUE TITLE
Capability to save queries

### ISSUE THREAD

**Issue by akarnid** [superfell/SoqlX#14]
I think it would be a nice addition if SOQLX could save queries to run later.  I use a set of queries which I need to run periodically, mostly stuff that you cannot get out of reports.  I keep these in a text file and paste them into the command window.  If I could access them from within SoqlX, even better.

Might mayhaps have a set limit, like 10 queries or so, just like the recent queries list.

**Comment by ksader-edmunds** [comment]
Can I vote this up about 100x?

**Comment by jschulerCLD** [comment]
I agree would be great if the 'recent query' list was longer or if you had some way to save prior queries in a local folder that you could reference later.

**Comment by virtzilla** [comment]
I'd also like to give this a big upvote. Would love an ability to have "bookmarks" for queries. 

Alternatively, if you add an ability to open an app specific bookmark - something like soqlexplorer:query="SELECT x from y", that would solve the need (and so much more).
