### ISSUE TITLE
User locked out error on authentication

### ISSUE THREAD

**Issue by jpekrul** [superfell/SoqlX#142]
**Describe the bug**
After using SOQLXplorer regularly for years, I no longer can because it can't authenticate to the Salesforce org. I get a message that "user name or password is incorrect, or user is locked out". But neither is true: I am able to logon to the org directly and I'm entering the correct user name and password.

**To Reproduce**
I enter username, and in the password field password.authentication token value

**Expected behavior**
login and begin using the tool

**Screenshots**

![Screen Shot 2021-10-29 at 12 58 18 PM](https://user-images.githubusercontent.com/19556325/139494910-aa0fd00d-a66d-4597-862a-0fd9f3638d4d.png)

**Desktop (please complete the following information):**
 - OS: [e.g. OSX 10.14]
 - SoqlX Version [e.g. 3.1]
Mac OS v11.6
**Additional context**
I am a Salesforce employee, and using this with an org known as GUS that we use internally as part of the software development process. It's not a sandbox.

**Comment by superfell** [comment]
That's the error message as reported by the Login API. You should check what login history says, it'll have more details on why the login is rejected. You might need an org admin to see the relevant login history info. You could also try updating to SoqlX v4.2 which uses OAuth for login rather than the Soap API.

**Comment by jpekrul** [comment]
thank you so much! I upgraded to V4.2 and it did solve the problem!
---
Jeff Pekrul
Principal Data Modeler | TMP Core Engineering - Salesforce
mobile: 415-559-7722


<https://smart.salesforce.com/sig/jpekrul//us_mb_kb/default/link.html>
