### ISSUE TITLE
Return the old style of login using credentials

### ISSUE THREAD

**Issue by spuliaiev-sfdc** [superfell/SoqlX#144]
**Is your feature request related to a problem? Please describe.**
Some environments do not have the client set up for OAuth. Therefore I got the error:
`error=invalid_client_id&error_description=client%20identifier%20invalid`

**Describe the solution you'd like**
Could you please add back to old style of login using the URL and credentials?

**Describe alternatives you've considered**
No alternatives - except using the version 4.1 of utility.

**Comment by superfell** [comment]
which env's don't have the client info? my understanding is that they are automatically replicated across prod & sandbox.

You can use the latest version of trapdoor to launch SoqlX if you want the old style username/password logins.

**Comment by superfell** [comment]
@spuliaiev-sfdc do you have more info on the environments where this is happening?

**Comment by spuliaiev-sfdc** [comment]
It's my locally running Salesforce application.

Sergii Puliaiev
   Workspace Engineering Team
   Lead Software Engineer

**Comment by superfell** [comment]
Launching SoqlX via trapdoor is the way to go for this.

**Comment by spuliaiev-sfdc** [comment]
Could you please elaborate? 
What is trapdoor?

And how to do
`Launching SoqlX via trapdoor`

**Comment by superfell** [comment]
see https://superfell.com/osx/trapdoor/
