### ISSUE TITLE
SOQL executed automatically on start

### ISSUE THREAD

**Issue by bluejackDE** [superfell/SoqlX#149]
**Describe the bug**
When I start SoqlXplorer and login to an org, it automatically executes the most recent query. Since I have accidentally tried to execute a too long query, this would always block me from working and after minutes, result in a timeout. How can I prevent SoqlXplorer from starting the query, or, alternatively: where are the recent queries stored so that I can delete them? 

**To Reproduce**
1. Have a query that is formally too long.
2. Force-quit SoqlXplorer, because you are impatient.
3. Start it again, login to the org
4. Wait hours until you will be able to delete the current query.

**Expected behavior**
Have an option to not execute the most recent query automatically after login.
Alternatively: Identify the location the recent queries are stored to manually delete them from the system.

**Desktop (please complete the following information):**
 - OS: macOS Monterrey 12.3.1 (21E258)
 - SoqlXplorer Version 4.3 (4.3)

edit: typo

**Comment by superfell** [comment]
It doesn’t intentionally run a query at startup. Are you selecting a stored token for login, or going through the new login flow?

**Comment by bluejackDE** [comment]
Stored token - and yes, I have reviewed the process on an org with a "safe" recent query. It doesn't execute it, but it seems to somehow try to interpret it already. My query holds 600k record ids in a WHERE clause - dumb mistake.

**Comment by bluejackDE** [comment]
I have now tried to circumvent this by logging in through a fresh login after removing the existing token - same behaviour. SoqlXplorer doesn't even retrieve the list of objects but immediately goes into no response mode (rotating beach ball).

**Comment by superfell** [comment]
You should be able to find the plist file with all the settings and queries somewhere under Library/Application Support you can delete this file while soqlx isn’t running and it should reset everything. Not near a Mac right now so can’t tell you the exact file name.  If it’s beachballing then it’s not running the query as that’s all on a background thread. Thinking about it, it’s probably the soql syntax parser/colorer that it’s tied up in.

**Comment by bluejackDE** [comment]
@superfell, thank you - file name would be great, because I could not locate any soql related files on my system, especially not in Library/Application Support and no plist file.

**Comment by superfell** [comment]
The file to delete is `~/Library/Preferences/com.pocketsoap.osx.SoqlXplorer.plist`
Alternatively you can run this from the terminal `defaults delete com.pocketsoap.osx.SoqlXplorer soql`
In either case you should do it with SoqlX closed. And afterwards launch SoqlX again.

**Comment by bluejackDE** [comment]
This did the job! Thanks for your support, @superfell. Just needed to leave out the soql attribute from the command.

**Comment by superfell** [comment]
with the parser perf improvements in the last release this shouldn't be an issue anymore
