### ISSUE TITLE
Update to support Salesforce API v58?

### ISSUE THREAD

**Issue by jeromegv** [superfell/SoqlX#157]
**Is your feature request related to a problem? Please describe.**
Some of the new fields/objects from more recent versions of the Salesforce API are not showing up

**Describe the solution you'd like**
I know this project is a labor of love but would love to see an update to API v58! Or if there any plan for it eventually

**Additional context**
Thank you for all your work with this tool!

**Comment by superfell** [comment]
I just pushed out a v4.5 release that is updated to API v58. Enjoy!
