### ISSUE TITLE
SOSL query export no longer exports "Type"

### ISSUE THREAD

**Issue by kenny-buckles** [superfell/SoqlX#159]
**Describe the bug**
When you export a SOSL query, the "Type" column is blank in the exported CSV

**To Reproduce**
1. Type a SOSL Query (e.g. FIND {email@example.com})
2. Click on Query
3. See results contain two columns. A "Type" and "Id" - both are populated
4. Export the results to a csv, and then open the file, the Type column header is there, but the type value is blank for all records

**Expected behavior**
Be able to export the SOSL results and have the "Type" field be populated with the object types of the records.

**Screenshots**
![SoLxJbs3_20230810](https://github.com/superfell/SoqlX/assets/92748327/c1e73041-cf6f-44fd-96b5-c1cc01f5b273)
![qGZv4U4D_20230810@2x](https://github.com/superfell/SoqlX/assets/92748327/a81e62ff-e72c-4780-8aec-14e228b527d3)

**Desktop (please complete the following information):**
 - OS: macOS Ventura Version 13.5 (22G74)
 - SoqlX Version 4.5 (4.5)

**Additional context**
It seems like my SoqlXplorer just updated. This was working previously.

**Comment by superfell** [comment]
Thanks for the report, do you know what version you were on previously? looks like this has been broken for a while.

**Comment by kenny-buckles** [comment]
Shoot. I don’t have any clue. Is there any way for me to see it anywhere? Are there any logs I could check?Kenny BucklesOn Aug 12, 2023, at 7:44 AM, Simon Fell ***@***.***> wrote:﻿
Thanks for the report, do you know what version you were on previously? looks like this has been broken for a while.

**Comment by superfell** [comment]
No problem, was just curious.
