### ISSUE TITLE
Results pane has disappeared

### ISSUE THREAD

**Issue by jesse-windebank** [superfell/SoqlX#163]
**Describe the bug**
When performing a query, I have noticed that the results pane has disappeared when running the latest version on Sonoma. Do you have any tips on how this can be restored?

Here is an example:

![2023-08-30_20-13-52](https://github.com/superfell/SoqlX/assets/60115932/bebd4302-badd-4197-b789-8be508b30414)
- You can see there are 40 results
- But no results pane is visible
- Save query results exports data to csv as expected

**Desktop (please complete the following information):**
 - OS: OSX Sonoma 14.0
 - SoqlX Version 4.6

Thanks for your help!

**Comment by superfell** [comment]
Can you drag the divider up to get it back? The divider is in line with the bottom of the query/queryall buttons.

**Comment by jesse-windebank** [comment]
Thanks Simon. That resolved the issue after some trial and error. Appreciate the help :)
