### ISSUE TITLE
Poor performance after some time

### ISSUE THREAD

**Issue by mstohr1975** [superfell/SoqlX#172]
**Describe the bug**
After a while of using SoqlXplorer, it seems to slow down and hang. Is there any option to clear cache or remove history? It seems not to use the max number of recent queries.

**Desktop (please complete the following information):**
 - OS: OSX 14.6.1
 - SoqlX Version: 4.6

**Comment by superfell** [comment]
Approximately how long is "some time" hours? days? is it with the app just sat idle, or running lots of queries?
The max number of recent queries is applied when a query is run. So if you change this to a smaller number it's not applied until you run another query. (but also at its largest setting, it's still trivially small). What hardware are you using?
Presumably if you quit and restart you get your performance back?

**Comment by mstohr1975** [comment]
After a couple of months of usage...running regularly queries. Poor performance stays after quit and restart. Running MacBook Air M2 MacOS 14.6.1. Last time I did deinstall the app and deleted all cache files on the OS and reinstalled. This resolved the problem. But now again after 3-4 months of usage, app is not reacting after login for more than a minute, every click, running a query takes up to 1-2 minutes...Max. number of recent queries to keep is set to default 10, but still I have 50-100 in history...is there a simple way to clear caches on file system?

**Comment by superfell** [comment]
close SoqlX then run this from a terminal window `defaults delete com.pocketsoap.osx.SoqlXplorer` that'll remove all the query history and restore everything to default (except for your oauth tokens).

I do see if you set the max queries to a large value, fill the history up, then change it to a small value it doesn't truncate to the new setting (but it also doesn't grow indefinately)

**Comment by mstohr1975** [comment]
This was it...many thanks...runs smoothly again.
