### ISSUE TITLE
PDF Errors

### ISSUE THREAD

**Issue by cwestonr** [superfell/SoqlX#33]
When saving as p df the first save of the pdf has a large blank space at the top of the document  and the end of the document is below the end of the final page .  WORKAROUND: save the PDF a second time and the data is correctly placed on the page.

**Comment by superfell** [comment]
I'm having a hard time reproducing this. Do you more details? what OS are you on, was there a specific sobject you saw this with ?

**Comment by cwestonr** [comment]
OS X Yosemite and lion and mountain lion 
all did the same 
from a sfdc test org  with custom objects with over 50 fields 
late 2007 MacBook bro 64 bit 4 gig  ram  ssd drive super drive  latest Java latest pine pico 
new battery 

I have had this problem always.  I installed soqlx   several times I can send you a copy of the PDFs if you like

Christopher W. Roberts Ph.D
cwestonr@me.com
C US: +801.637.3969


"You can have peace. Or you can have freedom. 
Don't ever count on having both at once." 
Robert A. Heinlein 
 
This message is for the designated recipient only and may contain privileged, proprietary, or otherwise private information. If you have received it in error, please notify the sender immediately and delete the original. Any other use of the email by you is prohibited.

**Comment by superfell** [comment]
If you have a sample one that'd be great,thanks.

**Comment by superfell** [comment]
I just saw this. One other work around is to use print -> save as PDF rather than the save PDF button directly. Will investigate more.

**Comment by cwestonr** [comment]
glad you found it and it was not just me!
Thanks!

Christopher W. Roberts Ph.D
cwestonr@me.com
C US: +801.637.3969


"You can have peace. Or you can have freedom. 
Don't ever count on having both at once." 
Robert A. Heinlein 
 
This message is for the designated recipient only and may contain privileged, proprietary, or otherwise private information. If you have received it in error, please notify the sender immediately and delete the original. Any other use of the email by you is prohibited.
