### ISSUE TITLE
"Save Query Results" does not save all the results

### ISSUE THREAD

**Issue by dkelll** [superfell/SoqlX#37]
I query for accounts  by ownerid and SoqlX shows in the bottom-left "11263 rows".  After I save the results, my spreadsheet editor shows only "9416 rows":

![soqlx](https://cloud.githubusercontent.com/assets/1993010/5674642/b01b355e-9773-11e4-89c1-8b39457ed2b6.png)

![googledocs](https://cloud.githubusercontent.com/assets/1993010/5674645/dfec71d0-9773-11e4-97d9-3e057e6fbc4e.png)

I tried another spreadsheet editor and it also confirmed only "9416 rows":

![numbers](https://cloud.githubusercontent.com/assets/1993010/5674675/8a70fdec-9774-11e4-835f-313734d463ec.png)

**Comment by superfell** [comment]
What was the query you ran?

**Comment by dkelll** [comment]
Sorry for the delay in getting back to you. I thought I had my statement saved but I can't seem to find it. I'll close the issue for now and if I come across it again I'll re-open.
