### ISSUE TITLE
Issue Lagging Scrolling to the right or left in the query results

### ISSUE THREAD

**Issue by zfrench** [superfell/SoqlX#39]
This issue occurs when I use an external monitor with SOQLXplorer.

Issue: When scrolling left or right in query results, it becomes very choppy/laggy.

Steps to replicate:
1. Drag SOQLXplorer to external monitor
2. Perform a query (preferably with a large number of fields)
3.  In the query results, attempt to scroll left or right

**Comment by superfell** [comment]
I had no issues scrolling the table left/right, its a standard NSTable, do you see similar problems in other apps ?
