### ISSUE TITLE
Slow typing occurs in query after including many (> 300) fields

### ISSUE THREAD

**Issue by zfrench** [superfell/SoqlX#40]
Issue: app takes a very long time to respond when double clicking on an object name to include all fields. If you attempt to enter in additional criteria it becomes very slow to respond. 

This is only happens when you have a lot of fields in the query.

**Comment by superfell** [comment]
i can't reproduce anything like this, do you have more details? what version of SoqlX, what version of the OS, what hardware are you running on ? what exactly do you mean by "enter in additional criteria" ?

**Comment by zfrench** [comment]
Yes, I am now running on SoqlX version 2.3. I am running on mac OS X 10.10.4, MacBook Pro (Retina 15-inch) Process 2.4 GHz i7, 16 GB RAM). When you attempt to type any characters in the frame, (i.e., you need enter a where clause to make a query more selective). I have one object specifically with over 200 fields, when I type anything the entry of the characters is delayed by several seconds. I can type multiple characters but each a take while for them to appear on the screen after I typed them on my keyboard.

**Comment by superfell** [comment]
I created a custom object with 300 fields and saw something of a slowdown when editing the soql, will investigate.
