### ISSUE TITLE
On Window close, application cannot be retrieved

### ISSUE THREAD

**Issue by tammersalem** [superfell/SoqlX#41]
For some reason when I open SoqlX, then close the window (using the red x), then click on the soqlX icon again the app doesn't open. The behaviour is no response whatsoever. The process is still running.
The only way to open the app again is to right click on the icon and "quit" and relaunch.

It's a minor issue.

SoqlX version: 2.2
OSX version: 10.10.2 (14C109)

**Comment by superfell** [comment]
When you close the window the app is still running, you can pick login from the File menu to open a new window. [probably it should quit when you close the last window]

**Comment by mkdjns** [comment]
I like the current behavior and it is similar to how other apps behave. I can see introducing a preference for what happens when the last window closes maybe.

**Comment by tammersalem** [comment]
You're absolutely right - I can click login and it comes back up.
It was just a bit surprising as most of my other OSX apps come back up -
thought it might be an issue.
