### ISSUE TITLE
Copying result values from related objects is not possible

### ISSUE THREAD

**Issue by katylava** [superfell/SoqlX#43]
I kinda get how it makes sense to not be able to click, select, and copy -- since that indicates the field may be editable. But there are many non-editable fields on the main object that you can still select and copy. So, it doesn't make sense why some non-editable fields are selectable and others aren't.

**Comment by superfell** [comment]
Currently you have to select the id field so that you can copy'n'paste from the data (which is the same rule for the primary table as well). It sucky i know.

**Comment by superfell** [comment]
I'll take another look at this, see if it can be smarter

**Comment by katylava** [comment]
Awesome... This will help us out quite a bit. We were saving to CSV to copy from there. Thank you.
