### ISSUE TITLE
queries fail because quotes get smart quoted

### ISSUE THREAD

**Issue by superfell** [superfell/SoqlX#46]
This is in v2.3, reported here https://twitter.com/richardjellis/status/630738255756021760

Enter a query like select id from contact where name='simon' and the quotes get mangled into smart quotes, which then fail when sent to sfdc. This started in v2.3. 

Perhaps something related to the Base SDK change to 10.9 or from resaving the xib's in xcode 6

**Comment by mkdjns** [comment]
While you're looking into this, can you also default "Smart Copy/Paste" to off? Drives me bonkers when trying to copy/paste in the Execute anonymous window.

<img width="445" alt="screen shot 2015-08-10 at 1 45 21 pm" src="https://cloud.githubusercontent.com/assets/884516/9183794/55953dbe-3f66-11e5-8fa9-8e8bac15d6a0.png">

**Comment by superfell** [comment]
Will do

**Comment by mkdjns** [comment]
Thank you!
