### ISSUE TITLE
Line indicator on Anonymous Apex Execute and Line Failure in Results Tab.

### ISSUE THREAD

**Issue by bfabergh** [superfell/SoqlX#47]
I would like to see the ability to indicate what line on an anonymous apex script fails, so it is easier to track down the line of code that breaks the script.

**Comment by ckoppelman** [comment]
And line numbers on the sidebar of the anon apex textbox!

**Comment by superfell** [comment]
Added in 4b3b3484787a3e6a74254f5da174b63a8a506715 will be in the next release.

**Comment by mkdjns** [comment]
This is awesome, but has broken the ability for me to choose a specific font in the Apex panel and in the output panel. Any way to add that back in?

**Comment by superfell** [comment]
I'll take a look. Do you sent a different font on each panel, or if there was a general font preference, would that cover it ?

**Comment by mkdjns** [comment]
A preference would be great! In fact, probably better than the old way where I did have to set the font in each panel.
