### ISSUE TITLE
Login fails on Yosemite; Unable to parse XML returned by server on login attempt

### ISSUE THREAD

**Issue by bferrell** [superfell/SoqlX#48]
Version 2.31

Userid and password are correct and tested.  Install is new on a fresh install of Yosemite.

2015-08-13 11:43:56.014 SoqlXplorer[417:4491] SecItemCopyMatching returned error -25300
2015-08-13 11:44:20.393 SoqlXplorer[417:4607] NSURLConnection/CFURLConnection HTTP load failed (kCFStreamErrorDomainSSL, -9813)
2015-08-13 11:44:20.394 SoqlXplorer[417:4491] Got invalid API response: Unable to parse XML
RequestURL: (null)
HTTP StatusCode: 0
responseData:
<s:Envelope xmlns:s='http://schemas.xmlsoap.org/soap/envelope/' xmlns:x='http://www.w3.org/2001/XMLSchema-instance' xmlns='urn:partner.soap.sforce.com'><s:Header><CallOptions><client>SoqlXplorer/2.3.1</client></CallOptions></s:Header><s:Body><login><username>yyyyyyyyyyyyyyy</username><password>xxxxxxxxx</password></login></s:Body></s:Envelope>
2015-08-13 11:44:20.394 SoqlXplorer[417:4491] Unable to parse XML returned by server
2015-08-13 11:44:20.395 SoqlXplorer[417:4491] (
	0   CoreFoundation                      0x00007fff9004903c __exceptionPreprocess + 172
	1   libobjc.A.dylib                     0x00007fff87e3376e objc_exception_throw + 43
	2   SoqlXplorer                         0x000000010b0f1b1a SoqlXplorer + 125722
	3   SoqlXplorer                         0x000000010b0f1240 SoqlXplorer + 123456
	4   SoqlXplorer                         0x000000010b0f5d34 SoqlXplorer + 142644
	5   SoqlXplorer                         0x000000010b0e4d80 SoqlXplorer + 73088
	6   SoqlXplorer                         0x000000010b0e4f2e SoqlXplorer + 73518
	7   libsystem_trace.dylib               0x00007fff92b96cd7 _os_activity_initiate + 75
	8   AppKit                              0x00007fff8d031eb1 -[NSApplication sendAction:to:from:] + 452
	9   AppKit                              0x00007fff8d047946 -[NSControl sendAction:to:] + 86
	10  AppKit                              0x00007fff8d047862 __26-[NSCell _sendActionFrom:]_block_invoke + 131
	11  libsystem_trace.dylib               0x00007fff92b96cd7 _os_activity_initiate + 75
	12  AppKit                              0x00007fff8d0477bf -[NSCell _sendActionFrom:] + 144
	13  libsystem_trace.dylib               0x00007fff92b96cd7 _os_activity_initiate + 75
	14  AppKit                              0x00007fff8d045cb3 -[NSCell trackMouse:inRect:ofView:untilMouseUp:] + 2821
	15  AppKit                              0x00007fff8d09e34f -[NSButtonCell trackMouse:inRect:ofView:untilMouseUp:] + 770
	16  AppKit                              0x00007fff8d044366 -[NSControl mouseDown:] + 714
	17  AppKit                              0x00007fff8d5ae2dc -[NSWindow _reallySendEvent:isDelayedEvent:] + 14125
	18  AppKit                              0x00007fff8cf3dc86 -[NSWindow sendEvent:] + 470
	19  AppKit                              0x00007fff8cf3a212 -[NSApplication sendEvent:] + 2504
	20  AppKit                              0x00007fff8ce63b68 -[NSApplication run] + 711
	21  AppKit                              0x00007fff8cde0244 NSApplicationMain + 1832
	22  libdyld.dylib                       0x00007fff840d55c9 start + 1
)

**Comment by superfell** [comment]
Did you change the login URL, or are you using the default one, seems like something on your network might be messing with SSL traffic.

**Comment by crbaptiste** [comment]
I just upgraded to Version 2.3.1 and am having the same issue.

Aug 24 13:18:50 xxxxxx SoqlXplorer[7131]: Got invalid API response: Unable to parse XML
	
	RequestURL: (null)
	
	HTTP StatusCode: 0
	
	responseData:
	
	<s:Envelope xmlns:s='http://schemas.xmlsoap.org/soap/envelope/' xmlns:x='http://www.w3.org/2001/XMLSchema-instance' xmlns='urn:partner.soap.sforce.com'><s:Header><CallOptions><client>SoqlXplorer/2.3.1</client></CallOptions></s:Header><s:Body><login><username>XXXXXXXXX</username><password>XXXXXXXXXX</password></login></s:Body></s:Envelope>
Aug 24 13:18:50 xxxxx SoqlXplorer[7131]: Unable to parse XML returned by server

I am certain that I am using the correct username/pass/token combination. Everything worked just fine this morning before I upgraded and now no luck.

**Comment by bferrell** [comment]
On 08/24/2015 10:20 AM, Charles Baptiste wrote:
>
> I just upgraded to Version 2.3.1 and am having the same issue.
>
> Aug 24 13:18:50 xxxxxx SoqlXplorer[7131]: Got invalid API response: Unable to parse XML
>
> |RequestURL: (null) HTTP StatusCode: 0 responseData: <s:Envelope xmlns:s='http://schemas.xmlsoap.org/soap/envelope/' xmlns:x='http://www.w3.org/2001/XMLSchema-instance'
> xmlns='urn:partner.soap.sforce.com'><s:Header><CallOptions><client>SoqlXplorer/2.3.1</client></CallOptions></s:Header><s:Body><login><username>XXXXXXXXX</username><password>XXXXXXXXXX</password></login></s:Body></s:Envelope>
> |
>
> Aug 24 13:18:50 xxxxx SoqlXplorer[7131]: Unable to parse XML returned by server
>
> I am certain that I am using the correct username/pass/token combination. Everything worked just fine this morning before I upgraded and now no luck.
>
> —
> Reply to this email directly or view it on GitHub <https://github.com/superfell/SoqlX/issues/48#issuecomment-134306626>.
>
I cured my issue by installing the apple java package

**Comment by superfell** [comment]
@bferrell There are zero dependencies on Java, that's a pure coincidence.

@crbaptiste are you still having problems, seems like lots of different tools hitting login issues today.

**Comment by crbaptiste** [comment]
It does look like the issues were on Salesforce's end. Sorry for the confusion.

**Comment by superfell** [comment]
@crbaptiste no worries, thanks for following up.
