### ISSUE TITLE
Winter'16 support?

### ISSUE THREAD

**Issue by rrajen** [superfell/SoqlX#50]
It looks like soql explorer (ver 2.3.1) does not show the list of SObjects that are available when I connect to a W'16 org. The list of SObjects is completely empty, however, soql queries work fine. If I connect to a Summer '15 org everything works as expected.

Environment: OS X 10.10.5

**Comment by superfell** [comment]
If the object list is completely empty then that's an API regression on the salesforce side.

Not sure what the winter release schedule is, but it hasn't made it to NA1 yet where my dev org is, so soqlX won't see any updates until then.

**Comment by rrajen** [comment]
@superfell - Version 1.94 of soql explorer seems to connect ok to winter 16 enabled orgs and functions as expected. Thought I'd pass it along as another piece of information.

**Comment by superfell** [comment]
older versions use a different API call to get the sobject list. Can you run the new version and look in the console log (/Application/Utilities/Console.app) there should be details about what exactly is failing.

**Comment by rrajen** [comment]
Hi Simon,

Console log shows the following error right after I login to a W'16 org:

9/18/15 8:21:38.261 AM SoqlXplorer[31663]: error doing descGT
UNKNOWN_EXCEPTION: An unexpected error occurred. Please include this
ErrorId if you contact support: 1885715728-190751 (-565331838)

Thanks
Raj

On Fri, Sep 18, 2015 at 6:56 AM, Simon Fell <notifications@github.com>
wrote:

> older versions use a different API call to get the sobject list. Can you
> run the new version and look in the console log
> (/Application/Utilities/Console.app) there should be details about what
> exactly is failing.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/superfell/SoqlX/issues/50#issuecomment-141457865>.
>



-- 
¯\_(ツ)_/¯ -- "Oh! I know what that is… it's a whatchamacallit" - Forgetful
Jones

**Comment by superfell** [comment]
Thanks, I'll pass that onto the salesforce API folks.

**Comment by superfell** [comment]
Thanks for reporting this, Salesforce has confirmed its a regression in the API, you can track its status at
https://success.salesforce.com/issues_view?id=a1p300000008ZWTAA2
