### ISSUE TITLE
Unable to maintain connection on OSX 10.10.5 Yosemite with 2.3.1

### ISSUE THREAD

**Issue by AlwaysThinkin** [superfell/SoqlX#51]
When I connect to my Orgs with 2.3.1 on OSX 10.10.5 Yosemite, I can see a successful login on my User reocrd but any attempt run a query returns the following error message.

INVALID_OPERATION_WITH_EXPIRED_PASSWORD: The users password has expired, you must call SetPassword before attempting any other API operations

Additionally, the SObjects panel does not get populated with any objects.

**Comment by superfell** [comment]
You'll need to login to the regular ui and update your expired password. Ideally SoqlX could do this natively

**Comment by AlwaysThinkin** [comment]
Ah, of course. We use SSO, I mostly use Dev Console and Copado for deployments, so I forget that my password looks expired through other apps. Thanks!
