### ISSUE TITLE
Closing one window when multiple are open causes crash

### ISSUE THREAD

**Issue by ImJohnMDaniel** [superfell/SoqlX#53]
If I have multiple connections open and I close one of them by clicking on the red dot upper left hand corner of window, the rest of the connections close and the app crashes.

Issue appears to have started with v2.4

**Comment by ImJohnMDaniel** [comment]
Actually, it would appear that the app is crashing even if there is only one connection and that is the one that is closed

**Comment by superfell** [comment]
Haven't been able to repro this yet. What OS are you on? would you happen to have the crash stack trace?

**Comment by ImJohnMDaniel** [comment]
OS X El Capitan v10.11.3

I don't have a stack trace handy.  Can you guide me through how to get one?

**Comment by superfell** [comment]
Normally when you get a crash, you get the apple bug reporter window that shows the crash details.

**Comment by superfell** [comment]
ok, i got a crash with multiple windows open, but not with one.

**Comment by ImJohnMDaniel** [comment]
Does this help?

[crash.txt](https://github.com/superfell/SoqlX/files/147355/crash.txt)

**Comment by superfell** [comment]
Yup,thanks

**Comment by ImJohnMDaniel** [comment]
Hey @superfell.  Just curious. Do you have an eta on the next release that will include this fix?  Cheers!

**Comment by superfell** [comment]
Currently the next planned release would be for API v37 in ~2 months time.

**Comment by ImJohnMDaniel** [comment]
I see.  :-(

If I ask nicely, can we get a patch release sooner than that?

**Comment by ImJohnMDaniel** [comment]
...maybe after #54 is fixed, perhaps?

**Comment by superfell** [comment]
I knew that was coming ;)

If you look in #54 you'll see a link for a build that includes both some changes related to that issue and this fix, You're welcome to use that until there's an official release.

**Comment by ImJohnMDaniel** [comment]
Mama always said, "It never hurts to ask."  ;-)

Just grabbed the build from 54.  Cheers for that!!
