### ISSUE TITLE
Apex Code Logging Level seems to be ignored

### ISSUE THREAD

**Issue by mkdjns** [superfell/SoqlX#56]
Recently, it seems no matter what I set for the Apex Code logging level, I end up seeing everything. As of now, I'm set to "Error" but am still seeing a boatload of "HEAP_ALLOCATE" lines.

According to [https://help.salesforce.com/apex/HTViewHelpDoc?id=code_setting_debug_log_levels.htm&language=en](https://help.salesforce.com/apex/HTViewHelpDoc?id=code_setting_debug_log_levels.htm&language=en), I should only be seeing "HEAP_ALLOCATE" at Finer and higher.

**Comment by superfell** [comment]
What instance is this with? and what version of SoqlX? this is perhaps a server side issue you should report to salesforce. FWIW, i can't repro this against NA1.

All levels set to None, apex code set to Error, my log has
36.0 APEX_CODE,ERROR
Execute Anonymous: system.debug('foo');
Execute Anonymous: string x;
Execute Anonymous: x = '';
Execute Anonymous: x = x + 'bobo';
Execute Anonymous: system.debug(x);
11:47:44.11 (11051707)|EXECUTION_STARTED
11:47:44.11 (11067567)|CODE_UNIT_STARTED|[EXTERNAL]|execute_anonymous_apex
11:47:44.11 (11570961)|CODE_UNIT_FINISHED|execute_anonymous_apex
11:47:44.11 (12939082)|EXECUTION_FINISHED


if i set apex code to Finer, my log gets
36.0 APEX_CODE,FINER
Execute Anonymous: system.debug('foo');
Execute Anonymous: string x;
Execute Anonymous: x = '';
Execute Anonymous: x = x + 'bobo';
Execute Anonymous: system.debug(x);
11:49:03.14 (14129973)|EXECUTION_STARTED
11:49:03.14 (14144614)|CODE_UNIT_STARTED|[EXTERNAL]|execute_anonymous_apex
11:49:03.14 (14516763)|HEAP_ALLOCATE|[72]|Bytes:3
11:49:03.14 (14584628)|HEAP_ALLOCATE|[77]|Bytes:152
11:49:03.14 (14620427)|HEAP_ALLOCATE|[342]|Bytes:408
11:49:03.14 (14650646)|HEAP_ALLOCATE|[355]|Bytes:408
11:49:03.14 (14675953)|HEAP_ALLOCATE|[467]|Bytes:48
11:49:03.14 (14785430)|HEAP_ALLOCATE|[139]|Bytes:6
11:49:03.14 (14868349)|HEAP_ALLOCATE|[EXTERNAL]|Bytes:9
11:49:03.14 (15132083)|STATEMENT_EXECUTE|[1]
11:49:03.14 (15218314)|STATEMENT_EXECUTE|[1]
11:49:03.14 (15233882)|HEAP_ALLOCATE|[1]|Bytes:3
11:49:03.14 (15279215)|HEAP_ALLOCATE|[50]|Bytes:5
11:49:03.14 (15307056)|HEAP_ALLOCATE|[56]|Bytes:5
11:49:03.14 (15318001)|HEAP_ALLOCATE|[64]|Bytes:7
11:49:03.14 (15412170)|USER_DEBUG|[1]|DEBUG|foo
11:49:03.14 (15433494)|STATEMENT_EXECUTE|[2]
11:49:03.14 (15442088)|STATEMENT_EXECUTE|[3]
11:49:03.14 (15448098)|STATEMENT_EXECUTE|[4]
11:49:03.14 (15454277)|HEAP_ALLOCATE|[4]|Bytes:4
11:49:03.14 (15472528)|HEAP_ALLOCATE|[4]|Bytes:4
11:49:03.14 (15479124)|STATEMENT_EXECUTE|[5]
11:49:03.14 (15511177)|USER_DEBUG|[5]|DEBUG|bobo
11:49:03.14 (15562217)|CODE_UNIT_FINISHED|execute_anonymous_apex
11:49:03.14 (24108323)|EXECUTION_FINISHED

**Comment by mkdjns** [comment]
Yeah, I think you are right. Just came back (independent of your question) to update that things were now working as expected.
