### ISSUE TITLE
Can't permanently change font size

### ISSUE THREAD

**Issue by ImJohnMDaniel** [superfell/SoqlX#59]
Hey @superfell, quick question for you.  In previous versions, were we able to change the font size on the Query pane, Anonymous Apex pane, and execution output pane (on the Apex window) and that change remain after SoqlX was restarted?  I am running v2.5 and I can change the font size in those panes but the change does not stick after I restart the program.  Is this a bug?  Thanks for the help.  Cheers!

**Comment by superfell** [comment]
Huh, yeah, its a little weird, it remembers if you change it from the query pane, but not the other 2. Will look into it.

**Comment by ImJohnMDaniel** [comment]
@superfell - Just checking in on this one.  Any progress yet?  Thanks for the help.  Cheers!
