### ISSUE TITLE
query syntax highlighting

### ISSUE THREAD

**Issue by superfell** [superfell/SoqlX#6]
is more broken than right at this point, doesn't handle any of the soql-r or aggregate query constructs correctly.

**Comment by dnalot** [comment]
Have you considered a dependency for highlighting based on a grammar?

**Comment by superfell** [comment]
It should be using the grammar, not sure exactly what you mean by having a dependency for it.

**Comment by dnalot** [comment]
A third party library? What I saw in code looked like parsing from scratch. Maybe I missed it.

**Comment by superfell** [comment]
Correct, right now its doing parsing by hand, its not using any library or real grammar. The fix should include using the published grammar (and possibly a library).
