### ISSUE TITLE
SOQL Request Timeout produces Internal Error

### ISSUE THREAD

**Issue by ImJohnMDaniel** [superfell/SoqlX#60]
Hey @superfell 

I have been getting an internal error when there is a SOQL request timeout.  Below is the error output

Exception Name: Http error
Description: Unable to complete API request: 
Error Domain=NSURLErrorDomain 
Code=-1001 "The request timed out." 
UserInfo=
{
    NSUnderlyingError=0x608000a44950 
    {
        Error Domain=kCFErrorDomainCFNetwork 
        Code=-1001 "The request timed out." 
        UserInfo=
        {
            NSErrorFailingURLStringKey=https://forthepeople--uat.cs43.my.salesforce.com/services/Soap/u/38.0/00D630000009D2g, 
            NSErrorFailingURLKey=https://forthepeople--uat.cs43.my.salesforce.com/services/Soap/u/38.0/00D630000009D2g, 
            _kCFStreamErrorCodeKey=-2102, 
            _kCFStreamErrorDomainKey=4, 
            NSLocalizedDescription=The request timed out.
        }
    }, 
    NSErrorFailingURLStringKey=https://forthepeople--UAT.cs43.my.salesforce.com/services/Soap/u/38.0/00D630000009D2g, 
    NSErrorFailingURLKey=https://forthepeople--UAT.cs43.my.salesforce.com/services/Soap/u/38.0/00D630000009D2g, 
    _kCFStreamErrorDomainKey=4, 
    _kCFStreamErrorCodeKey=-2102, 
    NSLocalizedDescription=The request timed out.
}
User Info: (null)

0   CoreFoundation                      0x00007fffa950252b __exceptionPreprocess + 171
1   libobjc.A.dylib                     0x00007fffbdbdacad objc_exception_throw + 48
2   SoqlXplorer                         0x000000010c6d6e5b SoqlXplorer + 126555
3   SoqlXplorer                         0x000000010c6eee81 SoqlXplorer + 224897
4   SoqlXplorer                         0x000000010c6bc676 SoqlXplorer + 18038
5   libsystem_trace.dylib               0x00007fffbe6ea03d _os_activity_initiate + 61
6   AppKit                              0x00007fffa78224e7 -[NSApplication(NSResponder) sendAction:to:from:] + 456
7   AppKit                              0x00007fffa7372245 -[NSControl sendAction:to:] + 86
8   AppKit                              0x00007fffa737216d __26-[NSCell _sendActionFrom:]_block_invoke + 136
9   libsystem_trace.dylib               0x00007fffbe6ea03d _os_activity_initiate + 61
10  AppKit                              0x00007fffa73720c5 -[NSCell _sendActionFrom:] + 128
11  AppKit                              0x00007fffa73b492a -[NSButtonCell _sendActionFrom:] + 98
12  libsystem_trace.dylib               0x00007fffbe6ea03d _os_activity_initiate + 61
13  AppKit                              0x00007fffa7370a58 -[NSCell trackMouse:inRect:ofView:untilMouseUp:] + 2481
14  AppKit                              0x00007fffa73b4667 -[NSButtonCell trackMouse:inRect:ofView:untilMouseUp:] + 785
15  AppKit                              0x00007fffa736f4c8 -[NSControl mouseDown:] + 832
16  AppKit                              0x00007fffa798273d -[NSWindow(NSEventRouting) _handleMouseDownEvent:isDelayedEvent:] + 6341
17  AppKit                              0x00007fffa797ef8c -[NSWindow(NSEventRouting) _reallySendEvent:isDelayedEvent:] + 1942
18  AppKit                              0x00007fffa797e42a -[NSWindow(NSEventRouting) sendEvent:] + 541
19  AppKit                              0x00007fffa781ebf5 -[NSApplication(NSEvent) sendEvent:] + 1145
20  AppKit                              0x00007fffa7105009 -[NSApplication run] + 1002
21  AppKit                              0x00007fffa70cfa8a NSApplicationMain + 1237
22  libdyld.dylib                       0x00007fffbe4b8255 start + 1

I am using SoqlXplorer v2.6 on macOS Sierra v10.12

Could it be because of the difference in string case of the two different references to NSErrorFailingURLStringKey??   .... '-UAT' vs '-uat' ??

**Comment by superfell** [comment]
Haven't seen that one before will investigate, might be related to Sierra

**Comment by ImJohnMDaniel** [comment]
Yeah, I thought about that as well.  I do know that I upgraded SoqlX and MacOS within a couple of days of each other, so it is definitely possible.  Also, I have only been running this particular query for the past few days, so I would not have seen anything prior to that.

**Comment by superfell** [comment]
the networking and related error handling all had a big update in the last release so this shouldn't happen any more. closing.
