### ISSUE TITLE
Feature Request: Ability to save multiple login credentials

### ISSUE THREAD

**Issue by dennismphil** [superfell/SoqlX#63]
This is a very useful tool. Thank you for building this!

Right now the tool remembers the credentials from the last successful login. However, it will be a huge productivity boost if it could remember multiple of these(Use case: Test/ Stage/ Production orgs) and we could pick one from a dropdown.

**Comment by superfell** [comment]
It does this already, note that the username field is a dropdown, as you login with different accounts they'll appear in the dropdown [assuming you chose the option to save the credentials to the keychain]. The list of usernames is filtered by the login URL chosen, so if you have regular & sandbox logins, the sandbox logins won't show until you selected the test.salesforce.com login from the endpoint dropdown.

**Comment by dennismphil** [comment]
Thank you @superfell I noticed it is having that feature! Awesome tool.
