### ISSUE TITLE
Broken links on http://www.pocketsoap.com/osx/soqlx/

### ISSUE THREAD

**Issue by pbowyer** [superfell/SoqlX#66]
The first two links links in `DevAngel's AppExchange Explorer is` no longer work - they're redirected to the Salesforce Trailblazer community homepage (thanks, Salesforce).

Googling hasn't turned up the app or the updated links

**Comment by superfell** [comment]
I redid the blurb, it makes me a little sad that Dave's original Explorer is lost to the winds of time
