### ISSUE TITLE
Launch with serverURL / SessionID from command line

### ISSUE THREAD

**Issue by superfell** [superfell/SoqlX#69]
See this twitter thread https://twitter.com/superfell/status/1067150680555573248

Can we launch SoqlX with command line params for serverUrl / SessionID so that it can be integrated with SalesforceDX. If not command line params, then some other scriptable way.
It should also do the right thing in the event that soqlX is already running

**Comment by ImJohnMDaniel** [comment]
Can't wait for this one!

**Comment by ImJohnMDaniel** [comment]
@superfell -- I have the Beta build.  You mentioned that `it uses a custom URL scheme rather than regular command line params.`, does that imply that I have to configure my system in some manner to respond to the custom URL??

**Comment by superfell** [comment]
Nope, you shouldn't need to do anything except drop the app in /Applications

**Comment by superfell** [comment]
This doesn't seem to be a soqlx problem. I get the same results trying to use that Sid/Server combo from beatbox as well. I tested with my dev edition org which worked fine, perhaps a dx related issue?. can you try a dev edition org and see what happens there.

**Comment by superfell** [comment]
We can remove many of the moving pieces for testing. Drop this in a file

```
<Envelope xmlns="http://schemas.xmlsoap.org/soap/envelope/">
    <Header>
        <SessionHeader xmlns="urn:partner.soap.sforce.com">
            <sessionId></sessionId>
        </SessionHeader>
    </Header>
    <Body>
        <getUserInfo xmlns="urn:partner.soap.sforce.com" />
    </Body>
</Envelope>
```

fill in the sessionId element and then run

`curl -d @userinfo.xml https://speed-power-9481.cs94.my.salesforce.com/services/Soap/u/22.0 -H 'SOAPAction: ""' -H "Content-Type:text/xml"`

**Comment by superfell** [comment]
In the past at least, missing session hash usually means the request is going to the wrong instance.

**Comment by ImJohnMDaniel** [comment]
Strange.  Getting a SFDX related error to my DE org when I try the command `sfdx force:user:display -u myde --json`.  

Let me ask @wadewegner and his team on Trailblazer Community about that first and then circle back here.

**Comment by superfell** [comment]
Is it possible something actually did invalidate the session? I just turned on the dev hub in my de org, created a scratch org, and using the results of user:display worked fine.

**Comment by ImJohnMDaniel** [comment]
I don't believe so.   The SFDX CLI is able to open the org just fine.  I will get back to you soon.

**Comment by ImJohnMDaniel** [comment]
@superfell -- Just curious, how are you getting the session id for the orgs you are testing with?  Is it using the SFDX CLI?

**Comment by superfell** [comment]
I mostly tested by having Beatbox call the soap login API and dump the sessionId. Earlier this morning, I turned on the dev hub in my existing DE org, and then used sfdx to create a scratch org and used the access token reported by sfdx force:user:display. I tried the sessionId you posted with a raw soap request and got the same sessionId invalid response, so I don't think its a client side problem.

**Comment by ImJohnMDaniel** [comment]
@superfell -- I was able to reproduce what you are seeing as well.  It seems that the SFDX command that reveals the session id only works for SFDX scratch orgs.  If I create a scratch org and then try the command give above, it does work as expected.

I believe that this enhancement works -- THANK YOU!!!!

Let me know if you have questions.

**Comment by superfell** [comment]
Great!, glad you got it working. What's the next step on the sfdx side? Is there an issue or PR somewhere i can track?

**Comment by ImJohnMDaniel** [comment]
I posted a question on the SalesforceDX Trailblazer Community and I am waiting for a reply. Here is the [post](https://success.salesforce.com/0D53A000040UaRp). The next step is dependent on what answer they will give to the question.

Having said that, from a SOQLX perspective, I believe we have what we need here so feel free to close this ticket out.

The third step will be for me to create a custom SFDX CLI plugin to wrap this command function to make it easier to capture the session id.  That will happen this month sometime.  

As always @superfell, thanks for all of the help!!!  Cheers!
