### ISSUE TITLE
grab text in object pop-up

### ISSUE THREAD

**Issue by purelight** [superfell/SoqlX#7]
Firstly, thankyou superfell for a lovely tool.  I prefer it to Schema Builder, bc its all there in front of me. simple.
IF....
if very easy, love be able to grab the text in the object pop-up.  i have the training wheels on, and so I grab for my learning notes etc..  my workaround is i sceenshot and ocr'd.

**Comment by superfell** [comment]
You can do Edit -> Copy with the details window selected, and it'll copy the entire table data to the clipboard.
