### ISSUE TITLE
Need a way to specify API version when launching in via url scheme

### ISSUE THREAD

**Issue by ckoppelman** [superfell/SoqlX#72]
We have hit an annoying window -- a time between releases, when some sandboxes are on v44.0 and some on v45.0, and the production orgs are on v44.0.  This happens in every release cycle.

In trying to test `open soqlx://{domain}/sid/{sessionId}`, on one of my v44.0 sandboxes, I have noticed that it's throwing an exception: 

> UNSUPPORTED_API_VERSION: Invalid Api version specified on URL

I looked into the code and it's using `DEFAULT_API_VERSION` in [the code](https://github.com/superfell/SoqlX/blob/60c5164e516e2341cbf3421b3b8993a728777bcd/AppExplorer/AppDelegate.m#L115)

It would be awesome if I could pass an API version on the url like `soqlx://{domain}:{apiVersion}/sid/{sessionId}` or `soqlx://{domain}/v{apiVersion}/sid/{sessionId}` or maybe most appropriately,  `soqlx://{domain}/sid/{sessionId}?apiVersion=v{apiVersion}` so I can use this feature in future annoying windows.

**Comment by superfell** [comment]
The regular login process does an automatic API version downgrade in this scenario. Should do the same thing with this path as well.
