### ISSUE TITLE
Basic build instructions

### ISSUE THREAD

**Issue by boutcher** [superfell/SoqlX#73]
Could someone provide basic instructions on how to get this building/running inside XCode? 

I started with `git clone --recurse-submodules https://github.com/superfell/SoqlX.git`, got an error about how the submodule reference to Fragaria was invalid:

`Fetched in submodule path 'Fragaria', but it did not contain fcb49e452b844bfe21d4b5e1cad0054c4266d28c. Direct fetching of that commit failed.`

... then opened AppExplorer/AppExplorer.xcodeproj ... and when building, it gets numerous errors with the ZK libraries:

`error: Build input file cannot be found: '/Users/MYNAME/Projects/SoqlX/zksforce/zkSforce/ZKRenderEmailTemplateBodyResult.m'`

... and 4 more errors about missing files.

**Comment by superfell** [comment]
I fixed the Fragaria reference issue, I'd forgotten that this was pointing to my fork, and so when my PR got merged i deleted my branch, orphaning this reference.

I didn't run into any issues with ZKSforce related problems, although i did notice that when `git submodule update` fails for the Fragaria submodule, it leaves the ZKSforce submodule in a bad state as well, so perhaps you were seeing that.

I added some info to the readme for the build https://github.com/superfell/SoqlX#build

Thanks for the report, hopefully you should be good to go now. I'd be interested in hearing about what you're thinking of enhancing.
