### ISSUE TITLE
document query hot keys

### ISSUE THREAD

**Issue by damiong28** [superfell/SoqlX#77]
**Is your feature request related to a problem? Please describe.**
I would prefer a hotkey to run the query immediately versus moving the cursor to the Run Query button each time.

**Describe the solution you'd like**
A (possibly customizable?) hotkey that runs the query right away. 

**Describe alternatives you've considered**
I don't know of any alternative to this besides using the mouse cursor and clicking the Run Query button.

**Comment by superfell** [comment]
These exist, but i see that they're not documented or discoverable, i think there was a blog post at some point in the dim distant past about it.

Query           ⌘R
Query All     ⇧⌘R
Query More ⌘M

I'll leave this issue open to update the docs.

**Comment by boutcher** [comment]
@superfell - why wouldn't you create a new menu item "Query" or something, with "Query", "Query All", "Query More" in it, ... and assign hotkeys to those?   Then it's not only documented, but it's discoverable, in a standard way.
