### ISSUE TITLE
If lookup relationship field contains mix of null and non-null values, getting odd null field return instead of lookup field name

### ISSUE THREAD

**Issue by DallasDeuce** [superfell/SoqlX#83]
**Describe the bug**
When query contains a lookup relationship thru multiple levels and contains a mix of null and non-null values, getting an odd return value on the records that have non-null in relationship lookup field (screenshot below).

**To Reproduce**
1. Write a query that includes a lookup relationship with multiple lookup references (example:  pse__Expense_Report__r.Budget__r.Item_Master__r.Name) and the lookup should have mix of null and non-null values for the query set that is returned. 
2. The records with null value somewhere in this relationship tree will be blank in query results (as expected) but the records without a null value should show the grandparent field name, but instead getting odd response like one below in query results in the column... in this example would expect to get 'Item 123' but instead get this stuff below.

pse__Budget__c (null) fields={
    "Item_Master__r" = "SCMC__Item__c (null) fields={\n    Name = \"Item 123\";\n} toNull={(\n)}";
} toNull=(
)

3.  If you explicitly filter on this relationship column to filter for <> null, then you get lookup relationship field name as expected, but that's problematic to have to filter for that when you expect a mix of null and non-null lookup ref name values.  I don't recall this occurring in the past and just noticed in past month or so (Aug 2019) so not sure if this is long-standing issue or not. 

**Screenshots**
![image](https://user-images.githubusercontent.com/3445225/64447191-c766d880-d0a8-11e9-8697-37f470263229.png)

**Desktop (please complete the following information):**
 - OS: MacOS 10.14.6 (Mojave)
 - SoqlX Version: 3.2

**Comment by superfell** [comment]
Thanks for the detailed report, will look into it.
