### ISSUE TITLE
SObjects sidebar fails to populate while scrolling (Catalina problem?)

### ISSUE THREAD

**Issue by bolaurent** [superfell/SoqlX#84]
**Describe the bug**
SObjects sidebar sometimes fails to populate while scrolling.

<img width="548" alt="image" src="https://user-images.githubusercontent.com/1839790/66867405-11689700-ef50-11e9-8a6d-2f16d4c60c9b.png">

**To Reproduce**
1. Authorize
2. Scroll sidebar
3. *Sometimes* the newly visible part of sidebar is not populated. Further scrolling does not cause it to be populated. Opening a new window is a workaround.

**Desktop (please complete the following information):**
 - OS:  OSX 10.15 (19A583)
 - SoqlX Version Version 3.2 (3.2)

**Additional context**

I suspect this may be related to installing OSX 10.15; I don't recall ever seeing it before.

**Comment by superfell** [comment]
I don't have a Catalina box yet, is this still a problem with SoqlX 3.3 & the latest Catalina?

**Comment by bolaurent** [comment]
I think I just installed 3.3 today or yesterday, and the problem doesn't
happen consistently. I'll let you know in a few days.

Bo

**Comment by bolaurent** [comment]
Still happening.

SOQLXplorer Version 3.3 (3.3)
OSX 10.15.1 (19B88)

**Comment by kensation** [comment]
I too am experiencing this issue.

SoqlXplorer Version 3.3 (3.3)
macOS Catalina 10.15.2 (19C57)

**Comment by superfell** [comment]
I wasn't able to reproduce this on 10.15.6. Is anyone still seeing this problem?

**Comment by bolaurent** [comment]
I have not seen it for a while; seems likely a macOS update "fixed" it?

While I have your attention, let me thank you for this awesome tool. I depend on it every day.

Bo
(Salesforce developer/admin at ubuntu.com)
________________________________

**Comment by bolaurent** [comment]
btw, I am on 10.15.5
________________________________

**Comment by superfell** [comment]
Thanks Bo.

Closing this as it appears to be a now resolved Catalina issue.
