### ISSUE TITLE
Launching SoqlX by serverURL/SessionID from command line opens two SoqlX windows

### ISSUE THREAD

**Issue by ImJohnMDaniel** [superfell/SoqlX#85]
**Related Issue**
#69 -- Launch with serverURL / SessionID from command line

**Describe the bug**
As of release v3.3, when you launch SoqlX by serverURL/SessionID from command line, it opens two SoqlX windows: one with the session that you requested from the serverURL/SessionID info and one window that provides the login prompt modal. 

Once you cancel out of the second one, that instance closes and you are left with the first instance that is logged into the org requested.

**To Reproduce**
1. execute a command line launch of SoqlX as expressed in issue #69 

**Expected behavior**
Only one instance should open already logged into the org requested.

**Desktop (please complete the following information):**
 - OS: 10.15.1
 - SoqlX Version: 3.3

**Additional context**
This behavior is relied upon by the custom Salesforce DX CLI plugin: [soqlx-opener](https://www.npmjs.com/package/soqlx-opener)

**Comment by superfell** [comment]
Thanks for the report. On 10.14 it opens 2 windows then closes one. I'll take another look at this, its likely fallout from the move to async only network requests. I don't know when I'm going to move to 10.15, so i might have to send you some builds to try, as you're seeing something different to 10.14

**Comment by ImJohnMDaniel** [comment]
G'day @superfell.  Just curious if you were able to find out anything on this issue?

**Comment by superfell** [comment]
Hey, sorry, haven't had time to look at this yet.

**Comment by superfell** [comment]
@ImJohnMDaniel are you still seeing this?

**Comment by ImJohnMDaniel** [comment]
Yes. I have been seeing it.

I saw the fix just come through.  Thanks for this!!!
