### ISSUE TITLE
show execution log in SoqlX

### ISSUE THREAD

**Issue by sk29110** [superfell/SoqlX#87]
**Is your feature request related to a problem? Please describe.**
After finding out SoqlX I spent less time with native developer console. Only time I need to access developer console is to see the execution log. Is there any way to put the execution log just like what they have in the native developer console but in SoqlX so I never have to open up the developer console?

**Describe the solution you'd like**
If we can have UI like execution result used in the anonymous apex I am happy :)

**Describe alternatives you've considered**
I am trying to find a way to show execution log without their developer console.

**Additional context**

**Comment by superfell** [comment]
I don't actively develop on the sfdc platform anymore, so I'm not sure exactly what you're looking for here. I have a quick play with the developer console, and as far as queries go all its seems to do is track the history of the queries you've run. The recents window in SoqlX does this already. If you could provide more details on exactly what you're looking for that'd be helpful.

**Comment by superfell** [comment]
closing due to lack of response.
