### ISSUE TITLE
Default SOQL query words to UPPERCASE

### ISSUE THREAD

**Issue by dschach** [superfell/SoqlX#88]
**Is your feature request related to a problem? Please describe.**
I use SoqlX to copy/paste queries into VSCode, and I like my code properly highlighted - which means that I need my query words to be uppercase. (SELECT, FROM)

**Describe the solution you'd like**
Default the query generator to put the words SELECT and FROM in uppercase

It doesn't seem a major enhancement, but it would help a lot downstream.

**Comment by superfell** [comment]
Which VSCode plugin are you using? soql is defined to be case insentitive.

**Comment by dschach** [comment]
SOQL is case insensitive, but the tools I use to color my code are not, so they expect "SELECT" to be uppercase. The fields upper/lower don't matter. While an all-lowercase query works technically, the code "looks better" with them uppercase. I know this is purely window-dressing, but it does make for better readability.

**Comment by superfell** [comment]
And the VSCode plugin you're using is ....

**Comment by dschach** [comment]
Salesforce's standard ones and Dark (Molokai) theme.

**Comment by dschach** [comment]
Thanks @superfell ! I look forward to seeing the next version release!

**Comment by superfell** [comment]
@dschach this feature is also in the beta I posted recently if you want to try it now.
https://twitter.com/superfell/status/1413229967740084224
