### ISSUE TITLE
repeating returns columns. 

### ISSUE THREAD

**Issue by rodandersen** [superfell/SoqlX#92]
**Describe the bug**
Here is my query: 
select id, Solar_Project__r.service__r.id, service__c from case 
where service__c = null 
and solar_project__r.service__c <> null
and createddate = this_year

(I know there is no reason to __r.id just easy to reproduce the problem). If I remove that from the query it is normal. 
**To Reproduce**

**Expected behavior**
I would expect three columns of data returned. I get a lot more than that. Export to excell shows more that double letter columns for the return data

**Screenshots**
<img width="1305" alt="image" src="https://user-images.githubusercontent.com/25966363/99177759-e78d2100-26c9-11eb-96b3-b5c56943347c.png">

**Desktop (please complete the following information):**
 - OS: OSX 10.14.6
 - SoqlX Version 3.3

**Additional context**

**Comment by rodandersen** [comment]
I know there is no reason to __r.id, Just an easy way to get the problem

**Comment by superfell** [comment]
That's odd. In my testing it looks like the column is repeated for the number of rows with non-null values. This seems to be a regression in 3.3, i couldn't reproduce it in 3.2. Will need to investigate more.
